### PR TITLE
Update versions & gval benchmark

### PR DESCRIPTION
**Pull request by mctofu**
- Updates the benchmark to use the most recent versions of the evaluators.
- Updates the gval benchmark to be more similar to the others where compilation time is not included in the benchmark.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@antonmedv

**Comment by antonmedv** [comment]
Missed this one) looks like it already outdated. Can somebody update it to the largest?

**Comment by hsluoyz** [comment]
@tson1111 please make a new PR to update all packages to latest.

**Comment by tson1111** [comment]
@antonmedv @hsluoyz I've made a PR to update all packages. Please take a look. https://github.com/antonmedv/golang-expression-evaluation-comparison/pull/6

**Pull request closed without merging**
